### ISSUE TITLE
Create new set

### ISSUE THREAD

**Issue by jandegithub** [DerpleMQ2/buttonmaster#2]
Can create a duplicate set by accident

Create new -> enter name of set, press enter, box stays open, think it did not take, enter same set name, click save

Duplicate checking on set names needs to be added, can cause the same problem with create new, enter existing set name and click save

This is per character

> ['server_character'] = {
>             ['Locked'] = false,
>             ['Sets'] = {
>                 [1] = 'Main',
>                 [2] = 'Move',
>                 [3] = 'Mission',
>                 [4] = 'Other',
>                 [5] = 'dev',
>                 [6] = 'dev',
>             },

**Comment by jandegithub** [comment]
Duplicate checking on set names needs to be added, can cause the same problem with create new, enter existing set name and click save

**Comment by DerpleMQ2** [comment]
https://github.com/DerpleMQ2/buttonmaster/commit/507fa7af96c6f9f8556426a8034f74b794dd0308
