### ISSUE TITLE
status of button

### ISSUE THREAD

**Issue by jandegithub** [DerpleMQ2/buttonmaster#4]
Would be useful to have the button show red if a TLO is a certain value or even change the button text to what a TLO returns
e.g 
cooldown timer = TLO.Something == true show red
or 
button text = TLO.Something
or 
button red/ different icon based on TLO value

**Comment by DerpleMQ2** [comment]
You can do some of this with the custom Lua timer, have you looked at that?

**Comment by DerpleMQ2** [comment]
https://github.com/DerpleMQ2/buttonmaster/commit/36aefe094f1d0b345ad0d23c2f132e3eed3cf810
